local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  
  static_map: false
  
  #We'll configure this costmap to be a rolling window... meaning it is always centered at the robot 
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.032

  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
