# distance a circular robot should be clear of the obstacle
robot_radius: 0.22  

obstacle_layer:
  track_unknown_space:  true # true needed for disabling global path planning through unknown space
  obstacle_range: 6.0 # the robot will only update its map with information about obstacles that are within 'obstacle_range' meters of the base
  raytrace_range: 6.5    
 
  observation_sources: base_scan # list of sensors that are going to be passing information to the costmap
  
  base_scan:
    sensor_frame: base_laser_link
    data_type: LaserScan
    topic: /base_scan
    marking: true
    clearing: true
    # min_obstacle_height: 0.05
    # max_obstacle_height: 1.5

inflation_layer:
  cost_scaling_factor:  5.0 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.25  # max. distance from an obstacle at which costs are incurred for planning paths.
 
static_layer:
  map_topic: /map