shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# Local planner
base_local_planner: p16_llc_local_planner/LLCLocalPlanner
#p16_llc_local_planner/LLCLocalPlanner
#dwa_local_planner/DWAPlannerROS
# ALTERNATIVES: dwa_local_planner/DWAPlannerROS, base_local_planner/TrajectoryPlannerROS

# Global planner
base_global_planner: rrt_planner/RRTPlanner
#rrt_planner/RRTPlanner
# ALTERNATIVES: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner, navfn/NavfnROS, 
