shutdown_costmaps: false

controller_frequency: 10.0 #frequency in Hz to run controller
controller_patience:  30 #3.0 #time to wait to reach a goal

planner_frequency: 0.001 #1.0 #frequency in Hz to run global planner
planner_patience: 50 #5.0 #time to wait to get a new plan

oscillation_timeout: 10.0
oscillation_distance: 0.2

# Local planner
base_local_planner: dwa_local_planner/DWAPlannerROS
#p16_llc_local_planner/LLCLocalPlanner
#dwa_local_planner/DWAPlannerROS
# ALTERNATIVES: dwa_local_planner/DWAPlannerROS, base_local_planner/TrajectoryPlannerROS

# Global planner
base_global_planner: rrt_planner/RRTPlanner
#rrt_planner/RRTPlanner
# ALTERNATIVES: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner, navfn/NavfnROS, 
